### ISSUE TITLE
[Question] Is there an extension for Python testbed on the marketplace?

### ISSUE THREAD

**Issue by shinichy** [microsoft/vscode-wasm#118]
Hi, I'd like to try Python execution on the web shell described in https://code.visualstudio.com/blogs/2023/06/05/vscode-wasm-wasi. I found [the web shell extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.webshell) on the market place, but couldn't find the Python testbed extension. Is it not publicly available yet?

**Comment by dbaeumer** [comment]
No we didn't release it since it would mean to update with moving Python forward. But you can look at the code here: https://github.com/microsoft/vscode-wasm/blob/main/testbeds/python/package.json
