### ISSUE TITLE
Not a bug but a thank you :)

### ISSUE THREAD

**Issue by floooh** [microsoft/vscode-wasm#151]
Not sure if this is the right place, but I just want to mention a new VSCode extension I started last week which uses your extension to run the (quite ancient) asmx 8-bit assembler (http://xi6.com/projects/asmx/) as WASI blob as part of a "home computer IDE".

The extension is still heavily WIP:

https://marketplace.visualstudio.com/items?itemName=floooh.vscode-kcide

...and looks like this (the emulator is integrated as regular Emscripten WASM running in a webpanel):

![Screenshot 2023-11-20 at 16 02 17](https://github.com/microsoft/vscode-wasm/assets/1699414/b13950aa-62d9-4169-9898-913a582e5c64)

...the WASI extension currently needs to be manually installed (automatic installation as dependency fails because the WASI extension doesn't yet have a release-version, only pre-release).

I also got the WASI execution working in the VSCode browser version, only the debug adapter is causing me some grief there (unrelated to WASI though).

So: thanks a lot and I'm looking forward to the first stable release!

PS: I was also missing a "cwd" arg for launching the WASI blob, but googling around it looks like WASI currently doesn't have the concept of a current-working-directory, so all good, I found a different solution.

**Comment by dbaeumer** [comment]
Just wanted to let you know that I will look into a release version this month.
