### ISSUE TITLE
Q: ETA for a non-pre-release version?

### ISSUE THREAD

**Issue by floooh** [microsoft/vscode-wasm#152]
Just a quick question, and since I haven't found a better place to ask (is there one?): are there plans already when the extension could move out of pre-release?

I have a VSCode extension here (https://marketplace.visualstudio.com/items?itemName=floooh.vscode-kcide) which is now pretty much ready to use. The extension runs a cmdline assembler tool via the WASI extension and it's working fine. The only downside is that users must install the extension as pre-release, otherwise installing the `ms-vscode.wasm-wasi-core` extension won't work.

Even though I mention that caveat promimently in the documentation, users are still likely to stumble over that problem since it differs from how VSCode extensions are usually installed.

IMHO, releasing a non-prerelease version of the WASI extension wouldn't be much of a problem if the major version number stays at 0, and the extension is marked as "Preview" in the marketplace?

**Comment by dbaeumer** [comment]
I will look into this this month and decide if we can make a release version of the extension and what the consequences are. Moving the WASM support into VS Code core will very likely not happen. VS Code core is actually already "big" and moving more code into it only makes development on the core more complicated.

See https://github.com/microsoft/vscode-eslint/issues/1842#issuecomment-2095506576 for why we are currently not publishing to Open-VSX and what the options are.

**Comment by dbaeumer** [comment]
We decided to provide a release version of the extension and the wasm-wasi API npm module. 

To allow further improvements to the API the npm module wasm-wasi will provide different routes to import different API versions. The API provided by the default import `import { Wasm } from '@vscode/wasm-wasi'`  is deprecated together with all other types from that route. The npm module exports new routes to be able to serve different API versions. The current route for the API (which is the same as before) is `import { Wasm } from '@vscode/wasm-wasi/v1'` There might be new routes in the future to cover a `v2` version of the API or a `proposed` route to test proposed API. 

The `v1` import works with the current pre-release version of the WASM WASI Core extension (e.g. `0.13.3`) and will work with the upcoming release version of the WASM WASI Core extension (e.g. `1.0.0`)

**Comment by lppedd** [comment]
Thank you!

**Comment by dbaeumer** [comment]
To be prepared for the release of the WASM WASI Core extension exiting extensions that have a dependency onto the WASM WASI Core extension should move to `@vscode/wasm-wasi@1.0.0-pre.2` version of the npm module.

**Comment by floooh** [comment]
OMG it's happening!

<img width="520" alt="image" src="https://github.com/user-attachments/assets/85ce8bbb-6ac4-4f24-a2f5-8a45f87dbb95">

**Comment by lppedd** [comment]
Now I'm eagerly waiting for [this](https://code.visualstudio.com/blogs/2024/05/08/wasm#_using-vs-code-apis-directly-from-rust) to happen 👀

**Comment by dbaeumer** [comment]
Will close the issue.
