### ISSUE TITLE
Document how to use VS Code's component model tooling to use WASM services inside a VS Code extensions

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-wasm#157]
With the component model tooling we now have an easy way to integrate WASM services into VS Code extensions. We should document this via samples and a blog post.

**Comment by lppedd** [comment]
Hey @dbaeumer! We're interested in running some of our Kotlin code as WASM binaries in VSC.

Is this possible ATM? K/WASM requires GC.

**Comment by dbaeumer** [comment]
Yes, stay tuned. There will be a blog post soon on how to do that. If the Kotlin code compiles to something that has only a main function (e.g. is more like a OS program) we have already support for it. See https://code.visualstudio.com/blogs/2023/06/05/vscode-wasm-wasi

**Comment by lppedd** [comment]
Nice, thanks! We'd like to expose functions to the JS side. Or maybe interoperate with VS Code APIs directly.  
Note sure of those options will be covered, but I'll check the blog post once it's out.

**Comment by dbaeumer** [comment]
Both cases are covered.

**Comment by lppedd** [comment]
Damn, VS Code on 🔥

**Comment by dbaeumer** [comment]
The blog post is out: https://code.visualstudio.com/blogs/2024/05/08/wasm

**Comment by lppedd** [comment]
Thanks @dbaeumer. Had a read already and everything makes sense.

Had my hopes too high for the "Full extension in Rust" part, but I guess waiting for the WASI spec is better (AFAIU 0.3 targets early/mid 2025).
