### ISSUE TITLE
[wit2ts] wit2ts fails if return type is List<MyType>

### ISSUE THREAD

**Issue by wyatt-herkamp** [microsoft/vscode-wasm#163]
So I am not sure if this is actually a bug on the JSON generation with wasm-tools 

However, 
If you try to generate TS for the following code

```wit
package wyatt-herkamp:archiveexplorer;

interface types {
	variant file-type {
        file,
        directory
	}
    record file{
        name: string,
        ftype: file-type,
        size: u64
    }
}
world archiveexplorer {
	use types.{ file, file-type };

	export open-archive: func(path: string) -> list<file>;
}
```

wit2ts silently errors out with no message. After some digging. I learned that after parsing the result from wasm-tools it creates an error of `Error: Unsupported owner [object Object]`

Now I can generate the Typescript by returning a single record. So `export open-archive: func(path: string) -> file`

I don't know how WIT and WASI work enough to go further than this.

**Comment by dbaeumer** [comment]
@wyatt-herkamp thanks for the issue.

I improved the error reporting and fixed the qualified name generation for world owners.

**Comment by dbaeumer** [comment]
Will create a new version mid next week.

**Comment by dbaeumer** [comment]
New version is out. Latest is: `0.1.0-pre.13`
