### ISSUE TITLE
Update README?

### ISSUE THREAD

**Issue by Localghost385** [microsoft/vscode-wasm#164]
I have been struggling to install wit2ts for an hour now, is there any possibility to update the readme to explain stuff or provide links.

sorry if I am in the wrong place.

**Comment by dbaeumer** [comment]
I have also updated the readme. Please ping if something is still unclear. You might also want to look at the examples here: https://github.com/microsoft/vscode-extension-samples/blob/main/wasm-component-model/package.json#L51

**Comment by Localghost385** [comment]
Thanks for this.
