### ISSUE TITLE
WebAssembly.compile(): expected version 01 00 00 00, found 0d 00 01 00 @+4.

### ISSUE THREAD

**Issue by lamb** [microsoft/vscode-wasm#165]
Activating extension '***' failed: WebAssembly.compile(): expected version 01 00 00 00, found 0d 00 01 00 @+4.

when use cargo component build 

```
const filename = vscode.Uri.joinPath(context.extensionUri, 'target', 'wasm32-wasi', 'debug', '*.wasm');
const bits = await vscode.workspace.fs.readFile(filename);
const module = await WebAssembly.compile(bits);
```

**Comment by dbaeumer** [comment]
Which version of VS Code are you using?

**Comment by lamb** [comment]
> Which version of VS Code are you using?

version 1.89

**Comment by dbaeumer** [comment]
@lamb `'*.wasm'` to my knowledge this doesn't work with the VS Code file system (e.g. when reading files). Does it fail for you if you specify a concrete file name as well.

**Comment by lamb** [comment]
> @lamb `'*.wasm'` to my knowledge this doesn't work with the VS Code file system (e.g. when reading files). Does it fail for you if you specify a concrete file name as well. `'*.wasm'` 据我所知，这不适用于 VS Code 文件系统（例如，在读取文件时）。如果您也指定了具体的文件名，它是否会失败。

yes，specify a concrete file name “am.wasm” is fail，*  just hides my plugin name. use wastime can run am.wasm well, but in vscode run failed. In my wasm code use wasi preview 2 [wasi-http](https://github.com/WebAssembly/wasi-http), example from https://github.com/wacker-dev/wasi-examples/tree/main/http-client

**Comment by dbaeumer** [comment]
Does the code work for you in NodeJS ?

And please note that the wasm wasi core extension has NO support for preview2 yet.

**Comment by lamb** [comment]
> Does the code work for you in NodeJS ?代码在 NodeJS 中是否适合您？
> 
> And please note that the wasm wasi core extension has NO support for preview2 yet.请注意，wasm wasi 核心扩展尚不支持 preview2。

I want use it in vscode extension. Expecting support wasi preview 2.

**Comment by dbaeumer** [comment]
I tested it in NodeJS 20.13.1 and it fails with the same error message:

```
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

[CompileError: WebAssembly.compile(): expected version 01 00 00 00, found 0d 00 01 00 @+4]

Node.js v20.13.1
```

There is little I can do if it doesn't work in NodeJS either.

**Comment by lppedd** [comment]
Maybe it will work in Node 22.x.  
Obviously it's not available for VSC yet, but worth trying.

**Comment by lamb** [comment]
> Maybe it will work in Node 22.x. Obviously it's not available for VSC yet, but worth trying.

I test in node 22.x, also  fails with the same error message  [CompileError: WebAssembly.compile(): expected version 01 00 00 00, found 0d 00 01 00 @+4]

**Comment by lamb** [comment]
> I tested it in NodeJS 20.13.1 and it fails with the same error message:
> 
> ```
> node:internal/modules/run_main:129
>     triggerUncaughtException(
>     ^
> 
> [CompileError: WebAssembly.compile(): expected version 01 00 00 00, found 0d 00 01 00 @+4]
> 
> Node.js v20.13.1
> ```
> 
> There is little I can do if it doesn't work in NodeJS either.

I try use[ jco transpile a component into js(ES module)](https://bytecodealliance.org/articles/jco-1.0)，it can work in nodejs，but ES module cannot be used in vscode. I tried to understand the generated code but I didn't find how jco loads compiled wasm file. Can @vscode/wasm-component-model achieve effects similar to jco?

**Comment by dbaeumer** [comment]
How do you build the wasm file?

**Comment by lamb** [comment]
> How do you build the wasm file?
```
# Compile our Rust library to a Wasm Component
cargo component build
```

**Comment by dbaeumer** [comment]
That builds a component which is not a valid WASM executable. See https://component-model.bytecodealliance.org/tutorial.html

**Comment by lamb** [comment]
Will vscode support wasm component in the future?

**Comment by dbaeumer** [comment]
Conceptually WASM components are more like libraries. VS Code will support them but they still need to be `linked` to a WASM executable. WASI Preview 2 currently defines two types through worlds: http/proxy and cli/command.

**Comment by lppedd** [comment]
@dbaeumer OT, but what's the VS Code team's vision about WebAssembly and JS? Will WASM be seen as a preferred alternative over JS at some point?

I ask because I had a discussion with the well known three-letters company about the possibility of investigating WebAssembly adoption, but it seems there is little to no interest for that. A marketing push might be necessary (unfortunately).
