### ISSUE TITLE
Update NPM package @vscode/wasm-wasi-lsp 

### ISSUE THREAD

**Issue by antaalt** [microsoft/vscode-wasm#199]
Hello, following the release of 1.0 of [@vscode/wasm-wasi](https://www.npmjs.com/package/@vscode/wasm-wasi) package, [@vscode/wasm-wasi-lsp](https://www.npmjs.com/package/@vscode/wasm-wasi-lsp) was not updated (the code on Github seems up to date and ready for 1.0). It is unusable for now as vscode will get the latest version of ms-vscode.wasm-wasi-core which rely on 1.0, but wasm-wasi-lsp is still targeting the pre-release version.

The package should be updated to support latest features.

**Comment by dbaeumer** [comment]
Thanks for pointing this out. A new version `0.1.0-pre.8` is on its way.
