### ISSUE TITLE
wasm language-server example fails to find pre-opened file descriptor

### ISSUE THREAD

**Issue by nikomatsakis** [microsoft/vscode-wasm#215]
Hi @dbaeumer, now that #214 is closed, I get the following error when attempting to run the sample:

> Starting WASM based LSP server
>
> thread 'main' panicked at src/main.rs:24:32:
> called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to find a pre-opened file descriptor > through which \"/workspace\" could be opened" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

the error is occurring on this line: 

https://github.com/microsoft/vscode-extension-samples/blob/9378d7c9299e543713a9eae22eadda70b7fc9431/wasm-language-server/server/src/main.rs#L22-L24

Any thoughts?

**Comment by dbaeumer** [comment]
When you run it do you open a workspace in the target folder?

The deadlock issue got fixed in WASI libc. If you are using the latest Rust toolchain you could try to remove the code as well and see if it works.
