### ISSUE TITLE
Running ls returns an exit code of 1

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-wasm#84]
Trying to implement shell integration to show exit status on the left, but some commands always exit with 1

![image](https://github.com/microsoft/vscode-wasm/assets/2193314/d28f2467-f6f2-4da8-9dea-4fee1a9ab320)

![image](https://github.com/microsoft/vscode-wasm/assets/2193314/30c278a8-fb5d-41cf-904f-0a35a38667c3)

**Comment by dbaeumer** [comment]
Got fixed.
